name: Deploy Appealing Portal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Cache
        run: |
          yarn cache clean

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist